accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    # path('home/', views.HomeView.as_view(), name="home"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout', views.Logout.as_view(), name='logout'),
    path('mypage/<int:pk>/', views.MyPage.as_view(), name='my_page'),
]

kakeiboapp/urls.py
from django.urls import path
from . import views

app_name = "kakeiboapp"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('payment_list', views.PaymentList.as_view(), name='payment_list'),
    path('income_list/', views.IncomeList.as_view(), name='income_list'),
    path('rest_list/', views.RestList.as_view(), name='rest_list'),
    path('payment_create/', views.PaymentCreate.as_view(), name='payment_create'),
    path('income_create/', views.IncomeCreate.as_view(), name='income_create'),
    path('rest_create/', views.RestCreate.as_view(), name='rest_create'),
    path('payment_update/<int:pk>/', views.PaymentUpdate.as_view(), name='payment_update'),
    path('income_update/<int:pk>/', views.IncomeUpdate.as_view(), name='income_update'),
    path('rest_update/<int:pk>/', views.RestUpdate.as_view(), name='rest_update'),
    path('payment_delete/<int:pk>/', views.PaymentDelete.as_view(), name='payment_delete'),
    path('income_delete/<int:pk>/', views.IncomeDelete.as_view(), name='income_delete'),
    path('month_dashboard/<int:year>/<int:month>/', views.MonthDashboard.as_view(), name='month_dashboard'),
    path('transition/', views.TransitionView.as_view(), name='transition'),
    path('want_list/', views.WantList.as_view(), name='want_list'),
    path('want_create/', views.WantCreate.as_view(), name='want_create'),
]

kakeibopj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kakeiboapp.urls')),
    path('', include('accounts.urls')),
]

kakeiboapp/models.py
from django.db import models
from django.utils import timezone
from accounts.models import User
# Create your models here.
class PaymentCategory(models.Model):#支払いのカテゴリ
    name = models.CharField('カテゴリ名', max_length=16)

    def __str__(self):
        return self.name
    
class PaymentCardCategory(models.Model):
    name = models.CharField('カードカテゴリ名', max_length=16)
    
    def __str__(self):
        return self.name
    
class Payment(models.Model):#支払額
    user = models.ForeignKey(User, verbose_name='ユーザー', on_delete=models.PROTECT)
    date = models.DateField('日付')
    price = models.IntegerField('金額')
    category = models.ForeignKey(PaymentCategory, on_delete=models.PROTECT, verbose_name='カテゴリ')
    cardcategory = models.ForeignKey(PaymentCardCategory, on_delete=models.PROTECT, verbose_name='カードカテゴリ名')
    description = models.TextField('概要', null=True, blank=True)


class IncomeCategory(models.Model):
    name = models.CharField('カテゴリ名', max_length=32)

    def __str__(self):
        return self.name


class Income(models.Model):
    user = models.ForeignKey(User, verbose_name='ユーザー', on_delete=models.PROTECT)
    date = models.DateField('日付')
    price = models.IntegerField('金額')
    category = models.ForeignKey(IncomeCategory, on_delete=models.PROTECT, verbose_name='カテゴリ')
    description = models.TextField('概要', null=True, blank=True)
    
class BankCategory(models.Model):
    name = models.CharField('カテゴリ名', max_length=32)

    def __str__(self):
        return self.name

class Rest(models.Model):
    user = models.ForeignKey(User, verbose_name='ユーザー', on_delete=models.PROTECT)
    date = models.DateField('日付',default=timezone.now)
    rest = models.IntegerField('金額')
    category = models.ForeignKey(BankCategory, on_delete=models.PROTECT,verbose_name='銀行')
    
class Want(models.Model):
    user = models.ForeignKey(User, verbose_name='ユーザー', on_delete=models.PROTECT)
    name = models.CharField('名前', max_length=50, blank=False, null=False)
    price = models.IntegerField('金額')
    date = models.DateField('日付')
    created_at = models.DateField('日付',default=timezone.now)
    url = models.URLField('URL', max_length=1000, null=False)
    

kakeiboapp/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.views import generic
from django.contrib.auth import login
from django.urls import reverse_lazy

from .models import Payment, Income,IncomeCategory, PaymentCategory,Rest, Want
from .forms import PaymentSearchForm, IncomeSearchForm, PaymentCreateForm, IncomeCreateForm, TransitionGraphSearchForm, RestCreateForm,WantCreateForm
from django.contrib import messages 
from django.shortcuts import redirect 
from django.utils import timezone
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

import numpy as np
import pandas as pd
from django_pandas.io import read_frame
from .plugin_plotly import GraphGenerator



class IndexView(LoginRequiredMixin,generic.TemplateView):
    template_name = "kakeiboapp/index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        TODAY = str(timezone.now()).split('-')
        year = TODAY[0]
        month = TODAY[1]
        next_year, next_month = get_next(year, month)
        prev_year, prev_month = get_prev(year, month)
        
        # objects = Payment.objects.filter(
        #     date__year = year, date__month = month
        # ).order_by("date")
        # total = 0
        # for object in objects:
        #     total += object.price
        #クレカなので先月の利用額
        payments_objects = Payment.objects.filter(
            user=self.request.user,
            date__year = year, 
            date__month = prev_month,
        ).order_by("date")
        total_payment = 0
        ## 
        for payment_object in payments_objects:
            total_payment += payment_object.price
        
        rest_objects = Rest.objects.filter(user=self.request.user).order_by("date")
        rest_total = 0
        for object in rest_objects:
            rest_total += object.rest
        usable = rest_total - total_payment
        context = {
            "year": year,
            'month': month,
            # "total": total,
            "payments":payments_objects,
            "total_payment": total_payment,
            "rest": rest_total,
            "next_year": next_year,
            "next_month": next_month,
            "prev_year": prev_year,
            "prev_month": prev_month,
            "usable": usable,
        }
        # if not queryset:
        #     return context
        return context

class PaymentList(LoginRequiredMixin, generic.ListView):
    template_name = 'kakeiboapp/payment_list.html'
    model = Payment
    # user=self.request.user
    ordering = '-date'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        self.form = form = PaymentSearchForm(self.request.GET or None)

        if form.is_valid():
            year = form.cleaned_data.get('year')
            # 何も選択されていないときは0の文字列が入るため、除外
            if year and year != '0':
                queryset = queryset.filter(date__year=year)

            # 何も選択されていないときは0の文字列が入るため、除外
            month = form.cleaned_data.get('month')
            if month and month != '0':
                queryset = queryset.filter(date__month=month)

            # 〇〇円以上の絞り込み
            greater_than = form.cleaned_data.get('greater_than')
            if greater_than:
                queryset = queryset.filter(price__gte=greater_than)
            
            # 〇〇円以下の絞り込み
            less_than = form.cleaned_data.get('less_than')
            if less_than:
                queryset = queryset.filter(price__lte=less_than)
            
            # キーワードの絞り込み
            key_word = form.cleaned_data.get('key_word')
            if key_word:
                # 空欄で区切り、順番に絞る、and検索
                if key_word:
                    for word in key_word.split():
                        queryset = queryset.filter(description__icontains=word)
            
            # カテゴリでの絞り込み
            category = form.cleaned_data.get('category')
            if category:
                queryset = queryset.filter(category=category)

        return queryset
    
    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     self.form = form = PaymentSearchForm(self.request.GET or None)

    #     if form.is_valid():
    #         year = form.cleaned_data.get('year')
    #         if year and year != '0':
    #             queryset = queryset.filter(user=self.request.user, date__year=year)

    #         month = form.cleaned_data.get('month')
    #         if month and month != '0':
    #             queryset = queryset.filter(user=self.request.user,date__month=month)

    #     return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # search formを渡す
        context['search_form'] = self.form

        return context
    
class IncomeList(LoginRequiredMixin, generic.ListView):
    template_name = 'kakeiboapp/income_list.html'
    model = Income
    ordering = '-date'
    paginate_by = 10
    
    def get_queryset(self):
        queryset = super().get_queryset()
        self.form = form = PaymentSearchForm(self.request.GET or None)

        if form.is_valid():
            year = form.cleaned_data.get('year')
            # 何も選択されていないときは0の文字列が入るため、除外
            if year and year != '0':
                queryset = queryset.filter(date__year=year)

            # 何も選択されていないときは0の文字列が入るため、除外
            month = form.cleaned_data.get('month')
            if month and month != '0':
                queryset = queryset.filter(date__month=month)

            # 〇〇円以上の絞り込み
            greater_than = form.cleaned_data.get('greater_than')
            if greater_than:
                queryset = queryset.filter(price__gte=greater_than)
            
            # 〇〇円以下の絞り込み
            less_than = form.cleaned_data.get('less_than')
            if less_than:
                queryset = queryset.filter(price__lte=less_than)
            
            # キーワードの絞り込み
            key_word = form.cleaned_data.get('key_word')
            if key_word:
                # 空欄で区切り、順番に絞る、and検索
                if key_word:
                    for word in key_word.split():
                        queryset = queryset.filter(description__icontains=word)
            
            # カテゴリでの絞り込み
            category = form.cleaned_data.get('category')
            if category:
                queryset = queryset.filter(category=category)

        return queryset

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     self.form = form = IncomeSearchForm(self.request.GET or None)

    #     if form.is_valid():
    #         year = form.cleaned_data.get('year')
    #         if year and year != '0':
    #             queryset = queryset.filter(date__year=year)

    #         month = form.cleaned_data.get('month')
    #         if month and month != '0':
    #             queryset = queryset.filter(date__month=month)

    #     return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form

        return context
    
class RestList(LoginRequiredMixin, generic.ListView):
    template_name = 'kakeiboapp/rest_list.html'
    model = Rest
    ordering = '-date'
    paginate_by = 10

    # def get_queryset(self):
    #     queryset = Rest.objects.filter(user=self.request.user).order_by('-created_at')
    #     # queryset = super().get_queryset()
    #     # # self.form = form = IncomeSearchForm(self.request.GET or None)

    #     # if form.is_valid():
    #     #     year = form.cleaned_data.get('year')
    #     #     if year and year != '0':
    #     #         queryset = queryset.filter(date__year=year)

    #     #     month = form.cleaned_data.get('month')
    #     #     if month and month != '0':
    #     #         queryset = queryset.filter(date__month=month)

    #     return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['search_form'] = self.form

        return context
    
class WantList(LoginRequiredMixin, generic.ListView):
    template_name = 'kakeiboapp/want_list.html'
    model = Want
    ordering = '-date'
    paginate_by = 10

    # def get_queryset(self):
    #     queryset = Want.objects.filter(user=self.request.user).order_by('-date')
    #     # queryset = super().get_queryset()
    #     # # self.form = form = IncomeSearchForm(self.request.GET or None)

    #     # if form.is_valid():
    #     #     year = form.cleaned_data.get('year')
    #     #     if year and year != '0':
    #     #         queryset = queryset.filter(date__year=year)

    #     #     month = form.cleaned_data.get('month')
    #     #     if month and month != '0':
    #     #         queryset = queryset.filter(date__month=month)

    #     return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'WishList'
        # context['search_form'] = self.form

        return context
    
class PaymentCreate(LoginRequiredMixin, generic.CreateView):
    """支出登録"""
    template_name = 'kakeiboapp/register.html'
    model = Payment
    form_class = PaymentCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Payment Registration'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeiboapp:payment_list')

    # 追加
    # バリデーション時にメッセージを保存
    def form_valid(self, form):
        self.object = payment = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        # messages.info(self.request,
        #               f'支出を登録しました\n'
        #               f'日付:{payment.date}\n'
        #               f'カテゴリ:{payment.category}\n'
        #               f'金額:{payment.price}円')

kakeiboapp/templates/kakeiboapp/base.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <title>{% block title %}{% endblock %}</title>    
  </head>
  <body>
    <header class="page-header">
      <h1 class='title-name'>
        <a href="{% url 'kakeiboapp:index' %}" class="header-title title-name">家計簿アプリ</a>
      </h1>
      <div class="pulldownmenu">
        <select name="select" onChange="location.href=value;">
          {% comment %} <option value="#">ページを選択してください</option> {% endcomment %}
          <option value="{% url 'kakeiboapp:index' %}">ホーム</option>
          <option value="{% url 'kakeiboapp:payment_create' %}">支出登録</option>
          <option value="{% url 'kakeiboapp:income_create' %}">収入登録</option>
          <option value="{% url 'kakeiboapp:rest_create' %}">残高登録</option>
          <option value="{% url 'kakeiboapp:payment_list' %}">支出一覧</option>
          <option value="{% url 'kakeiboapp:income_list' %}">収入一覧</option>
          {% comment %} <option value="{% url 'kakeiboapp:month_dashboard' next_year next_month%}">月間支出</option> {% endcomment %}
          <option value="{% url 'kakeiboapp:transition' %}">収支推移</option>
        </select>
      </div>
  
      <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            {% comment %} <a class="navbar-brand" href="{% url 'kakeibo:payment_create' %}">支出登録</a> {% endcomment %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:index' %}">ホーム</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:payment_create' %}">支出登録</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:income_create' %}">収入登録</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:rest_create' %}">残高登録</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:want_create' %}">ほしいもの登録</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:payment_list' %}">支出一覧</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:income_list' %}">収入一覧</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:month_dashboard' now_year now_month %}">月間支出</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:transition' %}">収支推移</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'kakeiboapp:want_list' %}">欲しいものリスト</a>
                </li>
                {% if not user.is_authenticated %}
                {% comment %} <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                </li> {% endcomment %}
                {% else %}
                {% comment %} こんにちは！ {{ user.username }} さん {% endcomment %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'accounts:my_page' user.pk %}">My page</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'accounts:logout' %}">Log out</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </div>
    <div class="container">                  
        {% block content %}{% endblock %}    
    </div>
    <div>
      
    </div>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
  </body>
</html>

kakeiboapp/templates/kakeiboapp/income_list.html
{% extends 'kakeiboapp/base.html' %}
{% load kakeibo %}
{% block content %}

<form class="mt-2" id="search-form" action="" method="GET">
  <label class="label mr-4">年月</label>
  {{ search_form.year }}
  {{ search_form.month }}
  <button class="btn btn-info ml-4" type="submit">検索</button>
</form>

<p class="search-result mt-3"> {{ page_obj.paginator.count }}件の検索結果 </p>

<table class="table mt-3">
  <tr>
    <th>日付</th>
    <th>カテゴリ</th>
    <th>金額</th>
    <th>概要</th>
    <th>編集</th>
  </tr>
  {% for income in income_list %}
  {% if user.username == income.user.username %}
  <tr>
    <td>{{ income.date }}</td>
    <td>{{ income.category }}</td>
    <td>
      {% if income.price %}
      {{ income.price }}
      {% endif %}
    </td>
    <td>
      {% if income.description %}
      {{ income.description }}
      {% endif %}
    </td>
    <td>
        <div class="manage-btn-area">
          <div class="update-btn-area">
            <a class="btn btn-info" href="{% url 'kakeiboapp:income_update' income.pk %}">更新</a>
          </div>
          <div class="delete-btn-area">
            <a class="btn btn-danger" href="{% url 'kakeiboapp:income_delete' income.pk %}">削除</a>
          </div>
        </div>
      </td>
  </tr>
  {% endif %}
  {% endfor %}
</table>

<div class="mt-5">
  {% if page_obj.has_previous %}
  <a class="mr-2 font-weight-bold" href="?{% url_replace request 'page' page_obj.previous_page_number %}" title="前ページへ">前へ</a>
  {% endif %}

  <span style="color:#0d1a3c">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>

  {% if page_obj.has_next %}
  <a class="ml-2 font-weight-bold" href="?{% url_replace request 'page' page_obj.next_page_number %}" title="次ページへ">次へ</a>
  {% endif %}
</div>

<div class="" style='margin-top: 10px;'>
  <a class="btn btn-danger" href="{% url 'kakeiboapp:income_create'%}">収入登録</a>
</div>

{% endblock %}

{% block extrajs %}
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', e => {
    const searchForm = document.getElementById('search-form');

    //カテゴリがクリックされたら検索実行
    for (const check of document.getElementsByName('category')) {
      check.addEventListener('change', () => {
        searchForm.submit();
      });
    }

    // 選択済みのカテゴリがクリックされたらチェックを解除して検索実行
    const selectedCategory = document.querySelector(`input[name='category']:checked`)
    if (selectedCategory) {
      selectedCategory.onclick = () => {
        selectedCategory.checked = false
        searchForm.submit();
      }
    }
  });
</script>
{% endblock %}

kakeiboapp/templates/kakeiboapp/index.html
{% extends "kakeiboapp/base.html" %} 
{% block title %}トップページ{% endblock %}

{% block content %} 
{% if not user.is_authenticated %} 
    <div class="card" style="width: 60rem; margin: 5% auto;">
        <div class="card-body">
            <a href="{% url 'accounts:signup' %}">新規登録</a></br>
            <a href="{% url 'accounts:login' %}">ログイン</a>
        </div>
    </div>
    {% comment %} <p><a href="{% url 'accounts:signup' %}">新規登録</a></p>
    <p><a href="{% url 'accounts:login' %}">ログイン</a></p> {% endcomment %}
{% else %}
{% comment %} こんにちは！ {{ user.username }} さん {% endcomment %}
    <div class="card" style="width: 60rem; margin: 5% auto;">
        <div class="card-body">
        <h5 class="card-title">今月の支払い</h5>
        <p class="card-text">{{ total_payment }}円</p>
        </div>
    </div>
    <div class="card" style="width: 60rem; margin: 5% auto;">
        <div class="card-body">
        <h5 class="card-title">今月の予算</h5>
        <p class="card-text">{{ usable }}円</p>
        </div>
    </div>
    <div class="card" style="width: 60rem; margin: 5% auto;">
        <div class="card-body">
        <h5 class="card-title">貯金額</h5>
        <p class="card-text">{{ rest }}円</p>
        </div>
    </div>
{% endif %}
{% comment %} <h1>トップページ</h1> {% endcomment %}
{% comment %} <p><a href="{% url 'accounts:signup' %}">新規登録</a></p>
<p><a href="{% url 'accounts:login' %}">ログイン</a></p> {% endcomment %}
{% endblock %}

kakeiboapp/templates/kakeiboapp/payment_list.html
<!-- kakeibo/templates/kakeibo/payment_list.html -->
{% extends 'kakeiboapp/base.html' %}
{% load kakeibo %}
{% block content %}

<!-- 検索フォーム -->
<form class="mt-2" id="search-form" action="" method="GET">
  <div>
    <label class="label mr-4">年月</label>
    {{ search_form.year }}
    {{ search_form.month }}
    <button class="btn btn-info ml-4" type="submit">検索</button>
  </div>
  <div class="mt-4">
    <label class="label mr-4">金額</label>
    {{ search_form.greater_than }}
    <span class="ml-4 mr-4">～</span>
    {{ search_form.less_than }}
  </div>
  <div class="mt-4">
    {{ search_form.key_word }}
    {% comment %} <button class="btn btn-info ml-4" type="submit">検索</button> {% endcomment %}
  </div>
  <div class="mt-2 inline">
    {{ search_form.category }}
  </div>
</form>

<!-- 追加　表示件数 -->
<p class="search-result mt-3"> {{ page_obj.paginator.count }}件の検索結果 </p>

<!-- 一覧表示 -->
<table class="table mt-3">
  <tr>
    <th>日付</th>
    <th>カテゴリ</th>
    <th>支払い</th>
    <th>金額</th>
    <th>概要</th>
    <th>編集</th> 
  </tr>
  {% for payment in payment_list %}

    {% if user.username == payment.user.username %}
      <tr>
        <td>{{ payment.date }}</td>
        <td>{{ payment.category }}</td>
        <td>{{ payment.cardcategory}}</td>
        <td>{{ payment.price}}</td>
        <td>
          {% if payment.description %}
          {{ payment.description }}
          {% endif %}
        </td>
        <td>
          <div class="manage-btn-area">
            <div class="update-btn-area">
              <a class="btn btn-info" href="{% url 'kakeiboapp:payment_update' payment.pk %}">更新</a>
            </div>
            <div class="delete-btn-area">
              <a class="btn btn-danger" href="{% url 'kakeiboapp:payment_delete' payment.pk %}">削除</a>
            </div>
          </div>
        </td>
      </tr>
    {% endif %}
  {% endfor %}
</table>

<!-- ページネーション -->
<div class="mt-5">
  <!-- 1つ前 -->
  {% if page_obj.has_previous %}
  <a class="mr-2 prev" href="?{% url_replace request 'page' page_obj.previous_page_number %}" title="前ページへ">前へ</a>
  {% endif %}

  <!-- nページ目/トータルページ数 -->
  <span style="color:#0d1a3c">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>

  <!-- 1つ後 -->
  {% if page_obj.has_next %}
  <a class="ml-2 next" href="?{% url_replace request 'page' page_obj.next_page_number %}" title="次ページへ">次へ</a>
  {% endif %}
</div>

<div class="" style='margin-top: 10px;'>
  <a class="btn btn-danger" href="{% url 'kakeiboapp:payment_create'%}">支出登録</a>
</div>

{% endblock %}

<!-- javascript -->
{% block extrajs %}
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', e => {
    const searchForm = document.getElementById('search-form');

    //カテゴリがクリックされたら検索実行
    for (const check of document.getElementsByName('category')) {
      check.addEventListener('change', () => {
        searchForm.submit();
      });
    }

    // 選択済みのカテゴリがクリックされたらチェックを解除して検索実行
    const selectedCategory = document.querySelector(`input[name='category']:checked`)
    if (selectedCategory) {
      selectedCategory.onclick = () => {
        selectedCategory.checked = false
        searchForm.submit();
      }
    }
  });
</script>
{% endblock %}