accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    # path('home/', views.HomeView.as_view(), name="home"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout', views.Logout.as_view(), name='logout'),
    path('mypage/<int:pk>/', views.MyPage.as_view(), name='my_page'),
]

kakeiboapp/urls.py
from django.urls import path
from . import views

app_name = "kakeiboapp"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('payment_list', views.PaymentList.as_view(), name='payment_list'),
    path('income_list/', views.IncomeList.as_view(), name='income_list'),
    path('rest_list/', views.RestList.as_view(), name='rest_list'),
    path('payment_create/', views.PaymentCreate.as_view(), name='payment_create'),
    path('income_create/', views.IncomeCreate.as_view(), name='income_create'),
    path('rest_create/', views.RestCreate.as_view(), name='rest_create'),
    path('payment_update/<int:pk>/', views.PaymentUpdate.as_view(), name='payment_update'),
    path('income_update/<int:pk>/', views.IncomeUpdate.as_view(), name='income_update'),
    path('rest_update/<int:pk>/', views.RestUpdate.as_view(), name='rest_update'),
    path('payment_delete/<int:pk>/', views.PaymentDelete.as_view(), name='payment_delete'),
    path('income_delete/<int:pk>/', views.IncomeDelete.as_view(), name='income_delete'),
    path('month_dashboard/<int:year>/<int:month>/', views.MonthDashboard.as_view(), name='month_dashboard'),
    path('transition/', views.TransitionView.as_view(), name='transition'),
    path('want_list/', views.WantList.as_view(), name='want_list'),
    path('want_create/', views.WantCreate.as_view(), name='want_create'),
]

kakeibopj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kakeiboapp.urls')),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
  
  
class UserManager(BaseUserManager):

  
    use_in_migrations = True
  
    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
  
        user = self.model(
            email=email, 
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
  
    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)
  
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
  
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
  
        return self._create_user(email, password, **extra_fields)
  
  
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('user_name'), max_length=30, unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    
  
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
  
    objects = UserManager()
  
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
  
    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
  
    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()
  
    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name
  
    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import get_user_model
from accounts.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        # fields = ["email", "password"]
        fields = ['username', 'email']
        
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

accounts/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
# Create your views here.
from .forms import LoginForm, SignUpForm
from django.contrib.auth import get_user_model
from .models import *


    
# class HomeView(TemplateView):
#     template_name = "accounts/home.html"
    
class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("kakeiboapp:index")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())
    
class Login(LoginView):
    form_class=LoginForm
    template_name = 'accounts/login.html'
    
class Logout(LogoutView):
    template_name = 'accounts/logout.html'
    
# def login(request):
#     if request.method=="POST":
#         email = request.POST.get('email')
#         form = LoginForm(request, data=request.POST)
        
#         # if form.is_valid():
#             # user = 
        
# '''自分しかアクセスできないようにするMixin(My Pageのため)'''
class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        # 今ログインしてるユーザーのpkと、そのマイページのpkが同じなら許可
        user = self.request.user
        return user.pk == self.kwargs['pk']


'''マイページ'''
class MyPage(OnlyYouMixin, DetailView):
    model = User
    template_name = 'accounts/my_page.html'
    # モデル名小文字(user)でモデルインスタンスがテンプレートファイルに渡される

accounts/templates/accounts/base.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

    <title>{% block title %}{% endblock %}</title>    
  </head>
  <body>
    <div class="container">                  
        {% block content %}{% endblock %}    
    </div>                                   
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
  </body>
</html>

accounts/templates/accounts/home.html
{% extends "kakeiboapp/base.html" %} 
{% block title %}ホーム{% endblock %}

{% block content %}
<h1>ホーム</h1>
{% comment %} <p>
    <div>
        {% if not user.is_authenticated %}
        こんにちは！ ゲスト さん
        {% else %}
        こんにちは！ {{ user.username }} さん
        {% endif %}
    </div>
</p> {% endcomment %}
{% endblock %}

accounts/templates/accounts/index.html
{% extends "kakeiboapp/base.html" %} 
{% block title %}トップページ{% endblock %}

{% block content %} 
<h1>トップページ</h1>
<p><a href="{% url 'kakeiboapp:signup' %}">ユーザ作成</a></p>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "kakeiboapp/base.html" %}
<!-- コンテンツ -->
{% block content %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-primary text-light">
        <h4>Log in</h4>
      </div>
      <div class="card-body">
        <form action="" method="POST">
          {{ form.non_field_errors }}
          {% for field in form %}
            {{ field }}
            {{ field.errors }}
            <br>
          {% endfor %}
          <button type="button submit" class="btn btn-primary" >ログイン</button>
          <input type="hidden" name="next" value="{{ next }}" />
          {% csrf_token %}
          <div class="text-center">
            <p>Not a member? <a href="{% url 'accounts:signup' %}">Register</a></p>
            <p>or sign up with:</p>
            <button type="button" class="btn btn-link btn-floating mx-1">
              <i class="fab fa-facebook-f"></i>
            </button>
        
            <button type="button" class="btn btn-link btn-floating mx-1">
              <i class="fab fa-google"></i>
            </button>
        
            <button type="button" class="btn btn-link btn-floating mx-1">
              <i class="fab fa-twitter"></i>
            </button>
        
            <button type="button" class="btn btn-link btn-floating mx-1">
              <i class="fab fa-github"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% comment %} {% extends "kakeiboapp/base.html" %} 
{% block title %}ログイン{% endblock %}
{% block content %}
<h1>Login</h1>
    {% if error_message %}
    <p><strong style="color: red;">{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <label for="email">メールアドレス</label>
        {{ form.as_p }}
        <p><input type="text" name="email" id="email" value="email"></p>    
        <br>
        <label for="password">パスワード</label>
        <p><input type="password" name="password" id="password" value=""></p>
        <br>
        <input type="submit" value="login">
    </form>
{% endblock %} {% endcomment %}

accounts/templates/accounts/logout.html
{% extends "kakeiboapp/base.html" %}
{% block content %}
<div class='container'>
  <div class="col-md-6 offset-md-3">
    <div class='card mt-3 mb-3 bg-light'>
      <!-- カードヘッダー -->
      <div class='card-header bg-primary text-light'>
        <h4>Log out</h4>
      </div>
      <!-- カードボディー -->
      <div class='card-body'>
        <p>ログアウトしました。</p>
        <p>ご利用ありがとうございました。</p>
        <hr class='mt-2 mb-2'>
        <p><a href="{% url 'accounts:login' %}">もう一度ログインする</a></p>
      </div>
    </div>
  </div>
  <p><a href="{% url 'kakeiboapp:index' %}">トップページ</a></p>
</div>
{% endblock %}

accounts/templates/accounts/my_page.html
{% extends "kakeiboapp/base.html" %}

{% block content %}
<div class="container">
  <h1>My page</h1>
  <hr>

  <!-- アカウント情報 -->
  <div class="row">
    <div class="col"><h4>■　登録情報</h4></div>
    <!-- 後で更新ボタン追加 -->
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td style="width: 50%;">姓</td>
        <td style="width: 50%;">{{ user.last_name }}</td>
      </tr>
      <tr>
        <td>名</td>
        <td>{{ user.first_name }}</td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td>{{ user.email }}</td>
      </tr>
      <tr>
        <td>ユーザー名</td>
        <td>{{ user.username }}</td>
      </tr>
    </tbody>
  </table>

  <!-- パスワード -->
  <div class="row mt-4">
    <div class="col"><h4>■　パスワード</h4></div>
    <!-- 後で更新ボタン追加 -->
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td style="width: 50%;">パスワード</td>
        <td style="width: 50%;">非表示</td>
      </tr>
    </tbody>
  </table>

  <!-- 権限 -->
  <div class="row mt-4">
    <div class="col"><h4>権限</h4></div>
  </div>
  <table class="table table-bordered">
    <tbody>
      {% if user.is_staff %}
      <tr>
        <td style="width: 50%;">スタッフ権限</td>
        <td style="width: 50%;">{{ user.is_staff }}</td>
      </tr>
      {% endif %}
      {% if user.is_superuser %}
      <tr>
        <td>スーパーユーザー権限</td>
        <td>{{ user.is_superuser }}</td>
      </tr>
      {% endif %}
    </tbody>
  </table>


</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "kakeiboapp/base.html" %}
{% block title %}ユーザ登録{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-6">
        <br>
        <h1>ユーザ登録</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                <br>
            {% endfor %}
            <button type="submit">登録</button>
        </form>
    </div>
</div>
{% endblock %}